### ISSUE TITLE
GSoC 2021 - Possible project ideas

### ISSUE THREAD

**Issue by piyushsingariya** [linkerd/gsoc#8]
What are the possible project ideas for the upcoming GSoC 2021 and who are the mentors??

**Comment by adleong** [comment]
Hi @piyushsingariya! We're still deciding whether Linkerd will be participating in GSoC 2021 and what the potential projects might be.  If you have any suggestions for projects that you'd be interested in working on, please let us know!

**Comment by jimil749** [comment]
Hey @adleong! There were really interesting projects last year and some of them weren't picked up. Like the Auto-Update project, which involves building a k8s operator for auto updation or the AlertManager integration to create alerts. I was wondering whether these project might still be valid for GSoC 2021 and also at the same time, how much will linkerd benefit from having these projects accomplished?

**Comment by adleong** [comment]
Unfortunately, the deadline for GSoC 2021 has passed.  But we're always happy to help folks out with contributing to the project!  If you're looking for good issues to get started with, search for the "good first issue" label or hop into the Linkerd slack and ask for help!
